### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by NourSoltani** [VSainteuf/utae-paps#21]
Greetings Mr @VSainteuf 

During the inference, I've been following the instructions in order to do panoptic segmentation.
However, after I wrote the instruction (python test_panoptic.py --dataset_folder data --weight_folder weights/UTAE_PAPs --res_dir Output) It prompted this: 
Traceback (most recent call last):
  File "test_panoptic.py", line 148, in <module>
    main(config)
  File "test_panoptic.py", line 97, in main
    dt_test = PASTIS_Dataset(**dt_args, folds=test_fold)
  File "/home/nextav/LULC/U-TAE-main/src/dataset.py", line 80, in __init__
    if "-" in mono_date
TypeError: argument of type 'NoneType' is not iterable

So, I made some modifications; More precisely I changed the If condition by: mono_date=config.mono_date; I'm sure it's not pretty right, but it works :)
After some minutes of doing inference(and the gpu memory reached 10GB), I've faced this new error, and the Output folder stills empty:

Step [100/124], Loss: 7.8338, SQ 81.0,  RQ 53.0  , PQ 43.4
Epoch time : 289.6s
Traceback (most recent call last):
  File "test_panoptic.py", line 148, in <module>
    main(config)
  File "test_panoptic.py", line 134, in main
    save_results(fold + 1, test_metrics, tables, config)
  File "/home/nextav/LULC/U-TAE-main/train_panoptic.py", line 329, in save_results
    with open(
FileNotFoundError: [Errno 2] No such file or directory: 'Output/Fold_1/test_metrics.json'

Do you have any idea for where the error could be? And thank you in advance.

**Comment by Hadir-05** [comment]
@NourSoltani Hello Sir, have you succeeded in solving this problem?
Thank you in Advance.
